"""
サービスパッケージ。

要件ID: RQ-FT-MANAGE-ASSET-MASTER
設計ID: DS-MD-APP-CORE-FT-VIEW-ASSET-STATUS
要件概要: 業務処理を責務分離して提供する。
設計概要: 認証、備品管理、貸出返却、ユーザー管理サービスを集約する。
呼び出し先設計ID: DS-CL-AUTH-SERVICE-FT-AUTHENTICATE-USER, DS-CL-ASSET-SERVICE-FT-MANAGE-ASSET-MASTER, DS-CL-LOAN-SERVICE-FT-REGISTER-LOAN, DS-CL-USER-SERVICE-FT-MANAGE-USER-ACCOUNT
呼び出し元設計ID: DS-MD-APP-CORE-FT-VIEW-ASSET-STATUS
"""
