# servicesパッケージ初期化
#
# 要件トレーサビリティ:
#   要件ID: RQ-FT-LOGIN, RQ-FT-LIST-EQUIPMENT, RQ-FT-LEND-EQUIPMENT, RQ-FT-CREATE-USER
#   設計ID: DS-CL-AUTH-SERVICE-FT-LOGIN, DS-CL-EQUIPMENT-SERVICE-FT-LIST-EQUIPMENT, DS-CL-LOAN-SERVICE-FT-LEND-EQUIPMENT, DS-CL-USER-SERVICE-FT-CREATE-USER
#   要件概要: ビジネスロジックサービスパッケージ
#   設計概要: 認証・備品・貸出・ユーザーのサービスクラスを提供する
#   呼び出し先設計ID: DS-CL-AUTH-SERVICE-FT-LOGIN
#   呼び出し元設計ID: DS-IF-AUTH-LOGIN-FT-LOGIN
