import matplotlib.pyplot as plt
import numpy as np
from typing import Dict, Any, Tuple


class VisualizationManager:
    """
    Service for managing plot generation and properties.
    Generates Matplotlib figures from statistical data to be displayed in Streamlit.
    """

    def __init__(self):
        # Set a consistent style for all plots generated by the app
        plt.style.use("ggplot")

    def generate_histogram(
        self, histogram_data: Dict[str, Any], title: str = "Histogram"
    ) -> plt.Figure:
        """
        Generates a Matplotlib figure for a histogram.

        Args:
            histogram_data: Dictionary containing 'counts' and 'bin_edges'.
            title: The title for the plot.

        Returns:
            plt.Figure: A Matplotlib figure object containing the histogram.
        """
        fig, ax = plt.subplots()

        counts = histogram_data.get("counts", [])
        bin_edges = histogram_data.get("bin_edges", [])

        if not counts or len(counts) == 0:
            ax.text(
                0.5,
                0.5,
                "No Data Available",
                horizontalalignment="center",
                verticalalignment="center",
            )
            ax.set_title(f"{title} (No Data)")
        else:
            ax.bar(
                bin_edges[:-1],
                counts,
                width=np.diff(bin_edges),
                align="edge",
                color="#3498db",
                edgecolor="white",
            )
            ax.set_title(title)
            ax.set_xlabel("Value")
            ax.set_ylabel("Frequency")

        fig.tight_layout()
        return fig

    def generate_qq_plot(self, data_a: np.ndarray, data_b: np.ndarray) -> plt.Figure:
        """
        Generates a Matplotlib figure for a two-sample Q-Q plot.

        Args:
            data_a: Sorted sample A array for comparison (quantiles).
            data_b: Sorted sample B array for comparison (quantiles).

        Returns:
            plt.Figure: A Matplotlib figure object containing the Q-Q plot.
        """
        fig, ax = plt.subplots()

        if len(data_a) == 0 or len(data_b) == 0:
            ax.text(
                0.5,
                0.5,
                "No Data Available",
                horizontalalignment="center",
                verticalalignment="center",
            )
            ax.set_title("Q-Q Plot (No Data)")
        else:
            # Create a scatter plot of the two samples to visualize distribution differences via quantiles
            idx = np.arange(len(data_a))
            ax.scatter(idx, data_a, color="#e74c3c", label="Sample A (X)", alpha=0.6)
            ax.scatter(
                idx,
                data_b[: len(data_a)],
                color="#2ecc71",
                label="Sample B (Y)",
                alpha=0.6,
            )

            ax.set_title("Quantile-Quantile (Q-Q) Comparison")
            ax.set_xlabel("Rank / Sample Index (Sorted)")
            ax.set_ylabel("Value")
            ax.legend()

        fig.tight_layout()
        return fig
