"""
UIパッケージ。

要件ID: RQ-UI-ASSET-LIST-SCREEN
設計ID: DS-MD-STREAMLIT-UI-UI-ASSET-LIST-SCREEN
要件概要: GUI画面群を構成して利用者操作を受け付ける。
設計概要: ログイン画面、備品一覧画面、ユーザー管理画面をまとめる。
呼び出し先設計ID: DS-IF-LOGIN-SCREEN-UI-LOGIN-SCREEN, DS-IF-ASSET-LIST-SCREEN-UI-ASSET-LIST-SCREEN, DS-IF-USER-MANAGEMENT-SCREEN-UI-USER-MANAGEMENT-SCREEN
呼び出し元設計ID: DS-MD-APP-CORE-FT-VIEW-ASSET-STATUS
"""
