"""
モデルパッケージ。

要件ID: RQ-DT-ASSET-ENTITY
設計ID: DS-SC-ASSETS-DT-ASSET-ENTITY
要件概要: 業務エンティティを型として扱えること。
設計概要: ユーザー、備品、一覧表示モデルを定義する。
呼び出し先設計ID: DS-SC-USERS-DT-USER-ACCOUNT-ENTITY, DS-SC-ASSETS-DT-ASSET-ENTITY, DS-FN-VIEW-ASSET-STATUS-FT-VIEW-ASSET-STATUS
呼び出し元設計ID: DS-CL-ASSET-REPOSITORY-DT-ASSET-ENTITY, DS-CL-USER-REPOSITORY-DT-USER-ACCOUNT-ENTITY
"""
