"""
セキュリティパッケージ。

要件ID: RQ-NF-LOW-SECURITY-POLICY
設計ID: DS-FN-PASSWORD-HASH-NF-LOW-SECURITY-POLICY
要件概要: 認証情報を安全に扱う。
設計概要: ハッシュ化と検証処理を提供する。
呼び出し先設計ID: DS-FN-PASSWORD-HASH-NF-LOW-SECURITY-POLICY
呼び出し元設計ID: DS-CL-AUTH-SERVICE-FT-AUTHENTICATE-USER, DS-CL-USER-SERVICE-FT-MANAGE-USER-ACCOUNT
"""
