"""
リポジトリパッケージ。

要件ID: RQ-DT-ASSET-ENTITY
設計ID: DS-MD-APP-CORE-FT-VIEW-ASSET-STATUS
要件概要: 永続データの参照更新を一元化する。
設計概要: users、assets、loan_statusへのデータアクセス層を集約する。
呼び出し先設計ID: DS-CL-ASSET-REPOSITORY-DT-ASSET-ENTITY, DS-CL-USER-REPOSITORY-DT-USER-ACCOUNT-ENTITY, DS-CL-LOAN-REPOSITORY-DT-LOAN-STATUS-ENTITY
呼び出し元設計ID: DS-CL-ASSET-SERVICE-FT-MANAGE-ASSET-MASTER, DS-CL-AUTH-SERVICE-FT-AUTHENTICATE-USER, DS-CL-LOAN-SERVICE-FT-REGISTER-LOAN, DS-CL-USER-SERVICE-FT-MANAGE-USER-ACCOUNT
"""
